const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

const ADD_PLAYER_SUCCESS = "ADD_PLAYER_SUCCESS";
const REMOVE_PLAYER_SUCCESS = "REMOVE_PLAYER_SUCCESS";

const GO_TO_ROUTE = "GO_TO_ROUTE";

export {
  LOGIN_USER_SUCCESS,
  REGISTER_USER_SUCCESS,
  LOGOUT_USER_SUCCESS,
  ADD_PLAYER_SUCCESS,
  REMOVE_PLAYER_SUCCESS,
  GO_TO_ROUTE
};
