const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

const ADD_PLAYER_SUCCESS = 'ADD_PLAYER_SUCCESS';
const REMOVE_PLAYER_SUCCESS = 'REMOVE_PLAYER_SUCCESS';

const ADD_TRAINING_SUCCESS = 'ADD_TRAINING_SUCCESS';
const DELETE_TRAINING_SUCCESS = 'DELETE_TRAINING_SUCCESS';
const UPDATE_TRAINING_SUCCESS = 'UPDATE_TRAINING_SUCCESS';

const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
const SAVE_ELEVEN_SUCCESS = 'SAVE_ELEVEN_SUCCESS';
const UPDATE_STAT_SUCCESS = 'UPDATE_STAT_SUCCESS';

const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

const GO_TO_ROUTE = 'GO_TO_ROUTE';

export {
  LOGIN_USER_SUCCESS,
  REGISTER_USER_SUCCESS,
  LOGOUT_USER_SUCCESS,
  ADD_PLAYER_SUCCESS,
  REMOVE_PLAYER_SUCCESS,
  ADD_TRAINING_SUCCESS,
  DELETE_TRAINING_SUCCESS,
  UPDATE_TRAINING_SUCCESS,
  ADD_GAME_SUCCESS,
  DELETE_GAME_SUCCESS,
  SAVE_ELEVEN_SUCCESS,
  UPDATE_STAT_SUCCESS,
  BEGIN_AJAX_CALL,
  AJAX_CALL_ERROR,
  GO_TO_ROUTE
};
